export class YahooFinanceTypes {

  // Note: generated by ChatGPT
  static exchangeNameToYahooSuffix = [
    { 'exchange': 'NASDAQ',        'yahooSuffix': '' },
    { 'exchange': 'NYSE',          'yahooSuffix': '' },
    { 'exchange': 'AMEX',          'yahooSuffix': '' },

    { 'exchange': 'TSX',           'yahooSuffix': '.TO' },
    { 'exchange': 'TSXV',          'yahooSuffix': '.V' },

    { 'exchange': 'LSE',           'yahooSuffix': '.L' },
    { 'exchange': 'HKEX',          'yahooSuffix': '.HK' },
    { 'exchange': 'SSE',           'yahooSuffix': '.SS' },
    { 'exchange': 'SZSE',          'yahooSuffix': '.SZ' },
    { 'exchange': 'TSE',           'yahooSuffix': '.T' },     /* Tokyo Stock Exchange */
    { 'exchange': 'JSE',           'yahooSuffix': '.JO' },    /* Johannesburg Stock Exchange */

    { 'exchange': 'ASX',           'yahooSuffix': '.AX' },
    { 'exchange': 'AXB',           'yahooSuffix': '.AX' },    /* alternative name Australia */

    { 'exchange': 'BOVESPA',       'yahooSuffix': '.SA' },   /* São Paulo, Brazil */
    { 'exchange': 'BYMA',          'yahooSuffix': '.BA' },   /* Buenos Aires, Argentina */

    { 'exchange': 'VIE',           'yahooSuffix': '.VI' },   /* Vienna, Austria */
    { 'exchange': 'BRU',           'yahooSuffix': '.BR' },   /* Euronext Brussels, Belgium */
    { 'exchange': 'PAR',           'yahooSuffix': '.PA' },   /* Paris / Euronext, France */
    { 'exchange': 'AMS',           'yahooSuffix': '.AS' },   /* Amsterdam / Euronext, Netherlands */

    { 'exchange': 'FRA',           'yahooSuffix': '.F' },    /* Frankfurt, Germany */
    { 'exchange': 'XETRA',         'yahooSuffix': '.DE' },   /* Deutsche Börse Xetra, Germany */
    { 'exchange': 'SGG',           'yahooSuffix': '.SG' },   /* Stuttgart, Germany */
    { 'exchange': 'HELSINKI',      'yahooSuffix': '.HE' },   /* Helsinki, Finland */

    { 'exchange': 'CSE',           'yahooSuffix': '.CO' },   /* Copenhagen, Denmark */
    { 'exchange': 'OLSE',          'yahooSuffix': '.OL' },   /* Oslo, Norway */
    { 'exchange': 'STO',           'yahooSuffix': '.ST' },   /* Stockholm, Sweden */
    { 'exchange': 'SIX',           'yahooSuffix': '.SW' },   /* Swiss Exchange, Switzerland */
    { 'exchange': 'XETRA_DE',      'yahooSuffix': '.DE' },   /* Alternate code for Germany XETRA */

    { 'exchange': 'BSE',           'yahooSuffix': '.BO' },   /* Bombay Stock Exchange, India */
    { 'exchange': 'NSE',           'yahooSuffix': '.NS' },   /* National Stock Exchange, India */

    { 'exchange': 'SGX',           'yahooSuffix': '.SI' },   /* Singapore Stock Exchange */
    { 'exchange': 'KRX',           'yahooSuffix': '.KS' },   /* Korea Exchange (main) */
    { 'exchange': 'KOSDAQ',        'yahooSuffix': '.KQ' },   /* Korea, KOSDAQ */

    { 'exchange': 'SET',           'yahooSuffix': '.BK' },   /* Thailand Stock Exchange */
    { 'exchange': 'TWSE',          'yahooSuffix': '.TW' },   /* Taiwan Stock Exchange */
    { 'exchange': 'TWO',           'yahooSuffix': '.TWO' },  /* Taiwan OTC Exchange */

    { 'exchange': 'SGO',           'yahooSuffix': '.SN' },   /* Santiago Stock Exchange, Chile */

    { 'exchange': 'MX',            'yahooSuffix': '.MX' },   /* Mexico Stock Exchange */

    { 'exchange': 'QSE',           'yahooSuffix': '.QA' },   /* Qatar Stock Exchange */

    { 'exchange': 'MOEX',          'yahooSuffix': '.ME' }    /* Moscow Exchange, Russia */
  ]
}
